In [1]:
import datetime as dt

In [2]:
import time as tm

In [3]:
tm.time()

1513826015.58588

In [4]:
dtnow = dt.datetime.fromtimestamp(tm.time())

In [5]:
dtnow

datetime.datetime(2017, 12, 21, 8, 43, 35, 925253)

In [6]:
dtnow.month

12

In [7]:
delta = dt.timedelta(days = 100)

In [8]:
today = dt.date.today()

In [9]:
today

datetime.date(2017, 12, 21)

In [10]:
today-delta

datetime.date(2017, 9, 12)

In [11]:
class Person:
    department = 'School of information'
    
    def set_name(self, new_name):
        self.name = new_name
    
    def set_location(self, new_location):
        self.location = new_location

In [12]:
person = Person()
person.set_name('Christopher Brooks')
person.set_location('Ann Arbor, MI, USA')
print('{} lives in {} and works in the department {}'.format(person.name,person.location,person.department))

Christopher Brooks lives in Ann Arbor, MI, USA and works in the department School of information


In [13]:
my_function = lambda a,b,c:a+b

In [14]:
my_function (1,2,3)

3

In [15]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    return person.split()[0] + ' ' + person.split()[-1]

#option 1
for person in people:
    print(split_title_and_name(person) == (lambda x: x.split()[0] + ' ' + x.split()[-1])(person))

#option 2
list(map(split_title_and_name, people)) == list(map(lambda person: person.split()[0] + ' ' + person.split()[-1], people))

True
True
True
True


True

In [16]:
my_list = []
for number in range (0,1000):
    if number % 2 == 0:
        my_list.append(number)

my_list




[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

In [17]:
my_list = [number for number in range(0,1000) if number%2 == 0] 
my_list

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

# Arrays in numpy

In [18]:
import numpy as np

In [19]:
mylist = [1,2,3] 
x = np.array(mylist)
x

array([1, 2, 3])

In [20]:
y = np.array([4,5,6])

In [21]:
y

array([4, 5, 6])

m = np.array([1,2,3],[4,5,6])

In [22]:
m = np.array([[1,2,3],[4,5,6]])

In [23]:
m

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
m.shape

(2, 3)

In [25]:
n = np.arange(0,30,2)

In [26]:
 n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [27]:
n = n.reshape(3,5)

In [28]:
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [29]:
o = np.linspace(0,4,9)
o

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ])

In [30]:
np.ones((2,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [31]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [32]:
np.array([1,2,3]*3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [33]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [34]:
p = np.ones([2,3],int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [35]:
np.vstack([p,2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [36]:
np.hstack([p,2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

# Operations in Arrays

In [37]:
x+y

array([5, 7, 9])

In [38]:
m.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [39]:
m.T.shape

(3, 2)

In [40]:
m.dtype

dtype('int64')

In [41]:
a = np.array([-4,-2,1,3,5])

In [42]:
a.sum()

3

In [43]:
a.max()

5

In [44]:
a.min()

-4

In [45]:
a.mean()

0.59999999999999998

In [46]:
a.std()

3.2619012860600183

In [47]:
a.argmax()   #index of the maximum value

4

# Indexing / Slicing

In [48]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [49]:
s[0],s[4],s[0:3]

(0, 16, array([0, 1, 4]))

In [50]:
s[0]

0

In [51]:
s[-4:]

array([ 81, 100, 121, 144])

In [52]:
s[-5::-2]

array([64, 36, 16,  4,  0])

In [53]:
r = np.arange(36)
r.resize((6,6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [76]:
r[2,2]

0

In [77]:
r[3,3:6]

array([21, 22, 23])

In [78]:
r[0:2,:-1]

array([[ 0,  0,  0,  3,  4],
       [ 0,  0,  0,  9, 10]])

In [79]:
r[-1,::2]

array([30, 30, 30])

In [80]:
r[r>30]

array([], dtype=int64)

In [81]:
r[r>30]=30
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [82]:
r2 = r[:3,:3] 
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [83]:


r2[:]=0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [96]:

r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [97]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [98]:
r_copy[:] = 10
print(r_copy)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]


In [99]:
print(r)

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


# Iteration over arrays

In [100]:
test = np.random.randint(0,10,(4,3))
test

array([[0, 7, 4],
       [8, 3, 3],
       [1, 3, 8],
       [5, 4, 8]])

In [101]:
for row in test:
    print(row)

[0 7 4]
[8 3 3]
[1 3 8]
[5 4 8]


In [102]:
for i in range(len(test)):
    print(test[i])

[0 7 4]
[8 3 3]
[1 3 8]
[5 4 8]


In [103]:
for i,row in enumerate(test):
    print('row',i,'is',row)

row 0 is [0 7 4]
row 1 is [8 3 3]
row 2 is [1 3 8]
row 3 is [5 4 8]


In [104]:
test2 = test**2
test2

array([[ 0, 49, 16],
       [64,  9,  9],
       [ 1,  9, 64],
       [25, 16, 64]])

In [105]:
for i,j in zip(test,test2):
    print(i ,'+' ,j,'=', i + j)

[0 7 4] + [ 0 49 16] = [ 0 56 20]
[8 3 3] + [64  9  9] = [72 12 12]
[1 3 8] + [ 1  9 64] = [ 2 12 72]
[5 4 8] + [25 16 64] = [30 20 72]


# Basic Data Processing in Pandas

# The Series Data Structure

In [106]:
import pandas as pd
pd.Series?

In [107]:
animals = ['Tiger','Bear','Moose']
pd.Series(animals)

0    Tiger
1     Bear
2    Moose
dtype: object

In [108]:
numbers = [1,2,3]
pd.Series(numbers)

0    1
1    2
2    3
dtype: int64

In [109]:
import numpy as np

In [110]:
animals = ['Tiger','Bear','None']
pd.Series(animals)

0    Tiger
1     Bear
2     None
dtype: object

In [111]:
numbers = [1,2,None]
pd.Series(numbers)

0    1.0
1    2.0
2    NaN
dtype: float64

In [112]:
import numpy as np
np.nan == None

False

In [113]:
np.nan == np.nan

False

In [114]:
np.isnan(np.nan)

True

In [115]:
sports = {'Archery': 'Bhutan',
       'Golf':'Scotland',
       'Sumo':'Japan',
       'Taekwondo':'South Korea'}
s = pd.Series(sports)
s

Archery           Bhutan
Golf            Scotland
Sumo               Japan
Taekwondo    South Korea
dtype: object

In [116]:
s.index

Index(['Archery', 'Golf', 'Sumo', 'Taekwondo'], dtype='object')

In [117]:
s = pd.Series(['Tiger','Bear','Moose'],index = ['India','America','Canada'])
s

India      Tiger
America     Bear
Canada     Moose
dtype: object

# Querying A Series

In [118]:
s.iloc[2]

'Moose'

In [119]:
s.loc['Canada']

'Moose'

In [120]:
s = pd.Series([100,120,101,3])
s

0    100
1    120
2    101
3      3
dtype: int64

In [121]:
total = 0
for item in s:
    total += item
print (total)

324


In [122]:
import numpy as np
total = np.sum(s)
print(total)

324


In [123]:
s = pd.Series(np.random.randint(0,1000,10000))
s.head()

0    272
1    786
2    124
3    721
4    538
dtype: int64

In [124]:
len(s)

10000

In [125]:
 ##%%timeit -n 100
##summary = 0
##for item in s:
  ##  summary += item

In [126]:
##%%timeit -n 100
##summary = np.sum(s)

In [127]:
s += 2
s.head()

0    274
1    788
2    126
3    723
4    540
dtype: int64

In [128]:
for label,value in s.iteritems():
    s.set_value(label,value+2)
s.head()

0    276
1    790
2    128
3    725
4    542
dtype: int64

In [129]:
##%%timeit -n 10
##s = pd.Series(np.random.randint(0,1000,10000))
##for label,value in s.iteritems():
   ## s.loc[label] = value+2


In [130]:
##%%timeit -n 10
##s = pd.Series(np.random.randint(0,1000,10000))
## s += 2

In [131]:
s = pd.Series([1,2,3])
s

0    1
1    2
2    3
dtype: int64

In [132]:
s.loc['Animal'] = 'Bears'
s

0             1
1             2
2             3
Animal    Bears
dtype: object

In [133]:
purchase_1 = pd.Series({'Name':'Chris','Item Purchased':'Dog Food','Cost':22.50})
purchase_2 = pd.Series({'Name':'Kevyn','Item Purchased':'Kitty Litter','Cost':2.50})
purchase_3 = pd.Series({'Name':'Vinod','Item Purchased':'Bird Seed','Cost':5.00})
df = pd.DataFrame([purchase_1,purchase_2,purchase_3],index = ['Store 1','Store 1','Store 2'])
df.head()




Cost Item Purchased   Name
Store 1  22.5       Dog Food  Chris
Store 1   2.5   Kitty Litter  Kevyn
Store 2   5.0      Bird Seed  Vinod

In [134]:
df.loc['Store 1',['Cost','Name']] #takes row index and a list of column names

Cost   Name
Store 1  22.5  Chris
Store 1   2.5  Kevyn

In [135]:
df['Cost']

Store 1    22.5
Store 1     2.5
Store 2     5.0
Name: Cost, dtype: float64

In [136]:
df.loc['Store 1']['Cost']

Store 1    22.5
Store 1     2.5
Name: Cost, dtype: float64

In [137]:
df.loc['Store 1':,['Name','Cost']]

Name  Cost
Store 1  Chris  22.5
Store 1  Kevyn   2.5
Store 2  Vinod   5.0

In [138]:
df.loc[:,['Items Purchased':]]

SyntaxError: invalid syntax (<ipython-input-138-23800d3ce0c5>, line 1)

In [139]:
df.drop('Store 1')

Cost Item Purchased   Name
Store 2   5.0      Bird Seed  Vinod

In [140]:
copy_df = df.copy()
copy_df = copy_df.drop('Store 1')
copy_df

Cost Item Purchased   Name
Store 2   5.0      Bird Seed  Vinod

In [141]:
del copy_df['Name']
copy_df

Cost Item Purchased
Store 2   5.0      Bird Seed

In [142]:
df['Location'] = None
df

Cost Item Purchased   Name Location
Store 1  22.5       Dog Food  Chris     None
Store 1   2.5   Kitty Litter  Kevyn     None
Store 2   5.0      Bird Seed  Vinod     None

# Dataframe Indexing and Loading

In [143]:

df = pd.read_csv('Desktop/olympics.csv',index_col=0) ## loads the csv file
df.head()

â  01 !  02 !  03 !  Total  â.1  01 !.1  02 !.1  03 !.1  \
Team (IOC code)                                                             
Afghanistan      14     0     0     2      2    0       0       0       0   
Algeria          13     5     4     8     17    3       0       0       0   
Argentina        24    21    25    28     74   18       0       0       0   
Armenia           6     2     6     6     14    6       0       0       0   
Australasia       2     3     4     5     12    0       0       0       0   

                 Total.1  â.2  01 !.2  02 !.2  03 !.2  Total.2  
Team (IOC code)                                                 
Afghanistan            0   14       0       0       2        2  
Algeria                0   16       5       4       8       17  
Argentina              0   42      21      25      28       74  
Armenia                0   12       2       6       6       14  
Australasia            0    2       3       4       5       12

In [144]:
af = pd.read_csv('Desktop/olympics.csv',index_col=0,skiprows = 1) ## index will the the 0th column and skips the row 1
af.head()

14    0  0.1    2  2.1  0.2  0.3  0.4  0.5  0.6  14.1  0.7  0.8  \
Afghanistan                                                                     
Algeria       13    5    4    8   17    3    0    0    0    0    16    5    4   
Argentina     24   21   25   28   74   18    0    0    0    0    42   21   25   
Armenia        6    2    6    6   14    6    0    0    0    0    12    2    6   
Australasia    2    3    4    5   12    0    0    0    0    0     2    3    4   
Australia     26  147  163  187  497   18    5    3    4   12    44  152  166   

              2.2  2.3  
Afghanistan             
Algeria         8   17  
Argentina      28   74  
Armenia         6   14  
Australasia     5   12  
Australia     191  509

In [145]:
df.columns  ## shows all the columns

Index(['â', '01 !', '02 !', '03 !', 'Total', 'â.1', '01 !.1', '02 !.1',
       '03 !.1', 'Total.1', 'â.2', '01 !.2', '02 !.2', '03 !.2', 'Total.2'],
      dtype='object')

In [146]:
for col in df.columns:
    if col[:2] == '01':
         df.rename(columns={col:'Gold'+col[4:]},inplace=True)
    if col[:2] == '02':
         df.rename(columns={col:'Silver'+col[4:]},inplace=True)
    if col[:2] == '03':
         df.rename(columns={col:'Bronze'+col[4:]},inplace=True)
            
df.head()     

â  Gold  Silver  Bronze  Total  â.1  Gold.1  Silver.1  \
Team (IOC code)                                                           
Afghanistan      14     0       0       2      2    0       0         0   
Algeria          13     5       4       8     17    3       0         0   
Argentina        24    21      25      28     74   18       0         0   
Armenia           6     2       6       6     14    6       0         0   
Australasia       2     3       4       5     12    0       0         0   

                 Bronze.1  Total.1  â.2  Gold.2  Silver.2  Bronze.2  Total.2  
Team (IOC code)                                                               
Afghanistan             0        0   14       0         0         2        2  
Algeria                 0        0   16       5         4         8       17  
Argentina               0        0   42      21        25        28       74  
Armenia                 0        0   12       2         6         6       14  
Australasia             0        0    2       3         4         5       12

In [147]:
df['Gold']>2

Team (IOC code)
Afghanistan     False
Algeria          True
Argentina        True
Armenia         False
Australasia      True
Australia        True
Austria          True
Azerbaijan       True
Bahamas          True
Bahrain         False
Name: Gold, dtype: bool

In [148]:
only_gold = df.where(df['Gold']>2)
only_gold

â   Gold  Silver  Bronze  Total   â.1  Gold.1  Silver.1  \
Team (IOC code)                                                               
Afghanistan       NaN    NaN     NaN     NaN    NaN   NaN     NaN       NaN   
Algeria          13.0    5.0     4.0     8.0   17.0   3.0     0.0       0.0   
Argentina        24.0   21.0    25.0    28.0   74.0  18.0     0.0       0.0   
Armenia           NaN    NaN     NaN     NaN    NaN   NaN     NaN       NaN   
Australasia       2.0    3.0     4.0     5.0   12.0   0.0     0.0       0.0   
Australia        26.0  147.0   163.0   187.0  497.0  18.0     5.0       3.0   
Austria          27.0   18.0    33.0    36.0   87.0  22.0    59.0      78.0   
Azerbaijan        6.0    7.0    11.0    25.0   43.0   5.0     0.0       0.0   
Bahamas          16.0    6.0     2.0     6.0   14.0   0.0     0.0       0.0   
Bahrain           NaN    NaN     NaN     NaN    NaN   NaN     NaN       NaN   

                 Bronze.1  Total.1   â.2  Gold.2  Silver.2  Bronze.2  Total.2  
Team (IOC code)                                                                
Afghanistan           NaN      NaN   NaN     NaN       NaN       NaN      NaN  
Algeria               0.0      0.0  16.0     5.0       4.0       8.0     17.0  
Argentina             0.0      0.0  42.0    21.0      25.0      28.0     74.0  
Armenia               NaN      NaN   NaN     NaN       NaN       NaN      NaN  
Australasia           0.0      0.0   2.0     3.0       4.0       5.0     12.0  
Australia             4.0     12.0  44.0   152.0     166.0     191.0    509.0  
Austria              81.0    218.0  49.0    77.0     111.0     117.0    305.0  
Azerbaijan            0.0      0.0  11.0     7.0      11.0      25.0     43.0  
Bahamas               0.0      0.0  16.0     6.0       2.0       6.0     14.0  
Bahrain               NaN      NaN   NaN     NaN       NaN       NaN      NaN

In [149]:
only_gold['Gold'].count()

7

In [150]:
df['Gold'].count()

10

In [151]:
only_gold = only_gold.dropna()
only_gold

â   Gold  Silver  Bronze  Total   â.1  Gold.1  Silver.1  \
Team (IOC code)                                                               
Algeria          13.0    5.0     4.0     8.0   17.0   3.0     0.0       0.0   
Argentina        24.0   21.0    25.0    28.0   74.0  18.0     0.0       0.0   
Australasia       2.0    3.0     4.0     5.0   12.0   0.0     0.0       0.0   
Australia        26.0  147.0   163.0   187.0  497.0  18.0     5.0       3.0   
Austria          27.0   18.0    33.0    36.0   87.0  22.0    59.0      78.0   
Azerbaijan        6.0    7.0    11.0    25.0   43.0   5.0     0.0       0.0   
Bahamas          16.0    6.0     2.0     6.0   14.0   0.0     0.0       0.0   

                 Bronze.1  Total.1   â.2  Gold.2  Silver.2  Bronze.2  Total.2  
Team (IOC code)                                                                
Algeria               0.0      0.0  16.0     5.0       4.0       8.0     17.0  
Argentina             0.0      0.0  42.0    21.0      25.0      28.0     74.0  
Australasia           0.0      0.0   2.0     3.0       4.0       5.0     12.0  
Australia             4.0     12.0  44.0   152.0     166.0     191.0    509.0  
Austria              81.0    218.0  49.0    77.0     111.0     117.0    305.0  
Azerbaijan            0.0      0.0  11.0     7.0      11.0      25.0     43.0  
Bahamas               0.0      0.0  16.0     6.0       2.0       6.0     14.0

In [152]:
only_gold = df[df['Gold']>2]
only_gold

â  Gold  Silver  Bronze  Total  â.1  Gold.1  Silver.1  \
Team (IOC code)                                                           
Algeria          13     5       4       8     17    3       0         0   
Argentina        24    21      25      28     74   18       0         0   
Australasia       2     3       4       5     12    0       0         0   
Australia        26   147     163     187    497   18       5         3   
Austria          27    18      33      36     87   22      59        78   
Azerbaijan        6     7      11      25     43    5       0         0   
Bahamas          16     6       2       6     14    0       0         0   

                 Bronze.1  Total.1  â.2  Gold.2  Silver.2  Bronze.2  Total.2  
Team (IOC code)                                                               
Algeria                 0        0   16       5         4         8       17  
Argentina               0        0   42      21        25        28       74  
Australasia             0        0    2       3         4         5       12  
Australia               4       12   44     152       166       191      509  
Austria                81      218   49      77       111       117      305  
Azerbaijan              0        0   11       7        11        25       43  
Bahamas                 0        0   16       6         2         6       14

In [153]:
df['Country'] = df.index
df = df.set_index('Gold')
df.head()


â  Silver  Bronze  Total  â.1  Gold.1  Silver.1  Bronze.1  Total.1  \
Gold                                                                        
0     14       0       2      2    0       0         0         0        0   
5     13       4       8     17    3       0         0         0        0   
21    24      25      28     74   18       0         0         0        0   
2      6       6       6     14    6       0         0         0        0   
3      2       4       5     12    0       0         0         0        0   

      â.2  Gold.2  Silver.2  Bronze.2  Total.2       Country  
Gold                                                          
0      14       0         0         2        2  Afghanistan   
5      16       5         4         8       17      Algeria   
21     42      21        25        28       74    Argentina   
2      12       2         6         6       14      Armenia   
3       2       3         4         5       12  Australasia

In [154]:
df = df.reset_index()
df.head()

Gold   â  Silver  Bronze  Total  â.1  Gold.1  Silver.1  Bronze.1  Total.1  \
0     0  14       0       2      2    0       0         0         0        0   
1     5  13       4       8     17    3       0         0         0        0   
2    21  24      25      28     74   18       0         0         0        0   
3     2   6       6       6     14    6       0         0         0        0   
4     3   2       4       5     12    0       0         0         0        0   

   â.2  Gold.2  Silver.2  Bronze.2  Total.2       Country  
0   14       0         0         2        2  Afghanistan   
1   16       5         4         8       17      Algeria   
2   42      21        25        28       74    Argentina   
3   12       2         6         6       14      Armenia   
4    2       3         4         5       12  Australasia

In [261]:
d = pd.read_csv('Desktop/analysis.csv')
d

Unnamed: 0     City Name   Wellness   Cookware   Crockery  Electronics  \
0            0       Asansol   4.956842   4.410967   4.966021     9.326210   
1            1     Bhagalpur   0.000000   0.000000   0.003084     0.003084   
2            2  Bhubaneshwar   4.162359   8.194965  13.000041     8.388217   
3            3      Bilaspur   1.174011   3.870465   4.533087    12.607008   
4            4       Burdwan   7.243664   7.549431   9.280459    17.738343   
5            5       Cuttack   0.787539   3.334338   4.585993     9.041897   
6            6    Darjeeling   1.295136   8.428735  12.983429    18.659352   
7            7       Deoghar   0.885450   8.918176   8.383538    18.142220   
8            8       Dhanbad   0.284988   2.136013   2.750970     7.439937   
9            9      Durgapur   5.499619   4.886350   6.966444    17.859140   
10          10       Gangtok   0.385607  14.926062  16.498030    33.419184   
11          11      Guwahati   3.451491   8.155695  14.045989     0.062016   
12          12    Jamshedpur   1.149294   3.466295   4.294050     8.455445   
13          13        Jorhat   0.511969   1.646993   2.625684     3.058612   
14          14     Kharagpur   7.161369  12.086506  10.758329    33.677483   
15          15       Kolkata  10.557638  13.567060  18.667570    30.059571   
16          16        Nagpur   2.898543   8.545297   9.444006     9.313160   
17          17         Patna   6.222084  10.166036  16.315678    24.641902   
18          18        Raipur   1.438922   4.260528   5.176812     4.090424   
19          19        Ranchi   3.519253   8.701642  15.352618    -0.057965   
20          20     Sambalpur   4.967846  30.363329  29.881101    51.318405   
21          21       Silchar   4.624118  13.750523  19.602239    31.436846   
22          22      Siliguri   6.962590  11.831839  18.062679    36.671054   

    Farm Fresh     Fashion  Food Services      Shoes         ...          \
0     4.875992   65.887485       0.321805   0.052578         ...           
1     0.000000   80.971502       0.000000   1.482084         ...           
2     1.332556  236.798917       3.125235   9.178001         ...           
3     0.749061   91.584659       0.704988   3.211575         ...           
4     6.738923  106.258585       0.071279   0.559170         ...           
5     0.498090   60.443088       1.327800   1.963191         ...           
6     0.000000  150.641068       1.746653   1.984217         ...           
7     1.640327  120.210377       0.076467   4.348105         ...           
8     0.088500   29.799165       1.181627   0.178593         ...           
9     6.602162  113.167080       1.529470   2.867845         ...           
10    1.757347  261.505175       4.128672  10.446536         ...           
11    3.303046  218.248316       7.755597   7.695406         ...           
12    0.335354   46.527830       3.034632   1.737390         ...           
13    0.645133   43.378136       0.057150   0.754509         ...           
14    7.337815  211.929732      29.651620   5.989689         ...           
15   10.099553  444.901968       9.465909   8.818370         ...           
16    3.845942  174.647373       9.302375   8.324793         ...           
17    4.660856  256.682641       5.749779   8.854915         ...           
18    1.943917  126.127415       6.825529   7.933729         ...           
19    4.976697  231.870906       4.171031   7.085250         ...           
20   39.609752  437.610881       1.147256   3.192565         ...           
21    0.137636  286.042480       0.006133   2.276448         ...           
22   10.278085  504.925297       6.235079  12.258729         ...           

    Area (km2)  Child Population  Sex Ratio  Per Capita Income  \
0        49.00             60183        929             100000   
1       342.00             54818        880              63200   
2       135.00             81847        890              98095   
3       345.80            407835        94

In [156]:
del d['Wellness']


In [157]:
d.columns

Index(['Unnamed: 0', 'City Name', 'Cookware', 'Crockery', 'Electronics',
       'Farm Fresh', 'Fashion', 'Food Services', 'Shoes', 'Home Essentials',
       'Home Fashion', 'Healthcare', 'Trolley Bags', 'Plastics',
       'Processed Food', 'Sports', 'Staples', 'Stationery', 'Toys', 'Utensils',
       'Total City Sale', 'City Type', 'Literacy Rate (%)',
       'City Population (excluding agglomeration) as per 2011 Census ',
       'Avg. CPI for the Period', 'Area (km2)', 'Child Population',
       'Sex Ratio', 'Per Capita Income', 'Population Growth Rate',
       'Population', 'Population living in slums', 'Child Ratio', 'Slum Ratio',
       'Population Density'],
      dtype='object')

In [158]:
d['Fashion'].unique()

array([  65.88748509,   80.97150205,  236.79891748,   91.58465891,
        106.25858476,   60.44308835,  150.64106805,  120.21037652,
         29.7991651 ,  113.16707996,  261.5051753 ,  218.24831567,
         46.52782968,   43.37813554,  211.92973204,  444.90196753,
        174.64737293,  256.68264065,  126.12741468,  231.8709058 ,
        437.61088076,  286.04247978,  504.92529673])

In [159]:
##d = d.set_index(['City','Fashion'])

In [160]:
d.loc[2]['Fashion']

236.79891747944629

In [161]:
d.loc[2,'Fashion']

236.79891747944629

In [162]:
d

Unnamed: 0     City Name   Cookware   Crockery  Electronics  Farm Fresh  \
0            0       Asansol   4.410967   4.966021     9.326210    4.875992   
1            1     Bhagalpur   0.000000   0.003084     0.003084    0.000000   
2            2  Bhubaneshwar   8.194965  13.000041     8.388217    1.332556   
3            3      Bilaspur   3.870465   4.533087    12.607008    0.749061   
4            4       Burdwan   7.549431   9.280459    17.738343    6.738923   
5            5       Cuttack   3.334338   4.585993     9.041897    0.498090   
6            6    Darjeeling   8.428735  12.983429    18.659352    0.000000   
7            7       Deoghar   8.918176   8.383538    18.142220    1.640327   
8            8       Dhanbad   2.136013   2.750970     7.439937    0.088500   
9            9      Durgapur   4.886350   6.966444    17.859140    6.602162   
10          10       Gangtok  14.926062  16.498030    33.419184    1.757347   
11          11      Guwahati   8.155695  14.045989     0.062016    3.303046   
12          12    Jamshedpur   3.466295   4.294050     8.455445    0.335354   
13          13        Jorhat   1.646993   2.625684     3.058612    0.645133   
14          14     Kharagpur  12.086506  10.758329    33.677483    7.337815   
15          15       Kolkata  13.567060  18.667570    30.059571   10.099553   
16          16        Nagpur   8.545297   9.444006     9.313160    3.845942   
17          17         Patna  10.166036  16.315678    24.641902    4.660856   
18          18        Raipur   4.260528   5.176812     4.090424    1.943917   
19          19        Ranchi   8.701642  15.352618    -0.057965    4.976697   
20          20     Sambalpur  30.363329  29.881101    51.318405   39.609752   
21          21       Silchar  13.750523  19.602239    31.436846    0.137636   
22          22      Siliguri  11.831839  18.062679    36.671054   10.278085   

       Fashion  Food Services      Shoes  Home Essentials         ...          \
0    65.887485       0.321805   0.052578         0.026259         ...           
1    80.971502       0.000000   1.482084         0.027802         ...           
2   236.798917       3.125235   9.178001         6.705987         ...           
3    91.584659       0.704988   3.211575         4.547712         ...           
4   106.258585       0.071279   0.559170         0.023667         ...           
5    60.443088       1.327800   1.963191         2.501399         ...           
6   150.641068       1.746653   1.984217         0.068453         ...           
7   120.210377       0.076467   4.348105         0.953865         ...           
8    29.799165       1.181627   0.178593         0.027974         ...           
9   113.167080       1.529470   2.867845         3.192212         ...           
10  261.505175       4.128672  10.446536         0.146881         ...           
11  218.248316       7.755597   7.695406         4.699615         ...           
12   46.527830       3.034632   1.737390         0.490392         ...           
13   43.378136       0.057150   0.754509         0.013736         ...           
14  211.929732      29.651620   5.989689         6.565266         ...           
15  444.901968       9.465909   8.818370         2.921959         ...           
16  174.647373       9.302375   8.324793         1.835115         ...           
17  256.682641       5.749779   8.854915         0.028911         ...           
18  126.127415       6.825529   7.933729         0.740549         ...           
19  231.870906       4.171031   7.085250         1.195173         ...           
20  437.610881       1.147256   3.192565         0.002223         ...           
21  286.042480       0.006133   2.276448         0.000000         ...           
22  504.925297       6.235079  12.258729         7.204110         ...           

    Area (km2)  Child Population  Sex Ratio  Per Capita Income  \
0        49.00             60183        929             100000   
1       342.00             548

In [163]:
d.index.names['Wellness','Fashion']

TypeError: list indices must be integers or slices, not tuple

# Merging Dataframes

In [164]:
import pandas as pd

In [165]:
df = pd.DataFrame([{'Name':'Chris','Items Purchased':'Sponge','Cost':22.50},
                  {'Name':'Kevyn','Items Purchased':'Kitty Litter','Cost':2.50},
                  {'Name':'Filip','Items Purchased':'Spoon','Cost':5.00}],
                 index = ['Store 1','Store 1','Store 2'])
df

Cost Items Purchased   Name
Store 1  22.5          Sponge  Chris
Store 1   2.5    Kitty Litter  Kevyn
Store 2   5.0           Spoon  Filip

In [166]:
df['Date'] = ['December 1','January 1','mid-may']
df


Cost Items Purchased   Name        Date
Store 1  22.5          Sponge  Chris  December 1
Store 1   2.5    Kitty Litter  Kevyn   January 1
Store 2   5.0           Spoon  Filip     mid-may

In [167]:
df['Delivered'] = True
df

Cost Items Purchased   Name        Date  Delivered
Store 1  22.5          Sponge  Chris  December 1       True
Store 1   2.5    Kitty Litter  Kevyn   January 1       True
Store 2   5.0           Spoon  Filip     mid-may       True

In [168]:
df['Feedback'] = ['Positive',None,'Negative']
df

Cost Items Purchased   Name        Date  Delivered  Feedback
Store 1  22.5          Sponge  Chris  December 1       True  Positive
Store 1   2.5    Kitty Litter  Kevyn   January 1       True      None
Store 2   5.0           Spoon  Filip     mid-may       True  Negative

In [169]:
adf = df.reset_index()
##adf['Date'] = pd.Series({0:'December 1',2:'mid-may'})
adf


index  Cost Items Purchased   Name        Date  Delivered  Feedback
0  Store 1  22.5          Sponge  Chris  December 1       True  Positive
1  Store 1   2.5    Kitty Litter  Kevyn   January 1       True      None
2  Store 2   5.0           Spoon  Filip     mid-may       True  Negative

In [170]:
adf['Date'] = pd.Series({0:'December 1',2:'mid-may'})
adf

index  Cost Items Purchased   Name        Date  Delivered  Feedback
0  Store 1  22.5          Sponge  Chris  December 1       True  Positive
1  Store 1   2.5    Kitty Litter  Kevyn         NaN       True      None
2  Store 2   5.0           Spoon  Filip     mid-may       True  Negative

In [171]:
staff_df = pd.DataFrame([{'Name':'Kelly','Role':'Director of HR'},
                        {'Name':'Sally','Role':'Course liaison'},
                        {'Name':'James','Role':'Grader'}])
staff_df = staff_df.set_index('Name')
student_df = pd.DataFrame([{'Name':'James','School':'Business'},
                        {'Name':'Mike','School':'Law'},
                        {'Name':'Sally','School':'Engineering'}])
student_df = student_df.set_index('Name')
print (staff_df)
print  ()
print (student_df)



                 Role
Name                 
Kelly  Director of HR
Sally  Course liaison
James          Grader

            School
Name              
James     Business
Mike           Law
Sally  Engineering


In [172]:
pd.merge(staff_df,student_df,how = 'outer',left_index = True,right_index = True)   ##union

Role       School
Name                              
James          Grader     Business
Kelly  Director of HR          NaN
Mike              NaN          Law
Sally  Course liaison  Engineering

In [173]:
pd.merge(staff_df,student_df,how = 'inner',left_index = True,right_index = True) ##intersection

Role       School
Name                              
Sally  Course liaison  Engineering
James          Grader     Business

In [174]:
pd.merge(staff_df,student_df,how = 'left',left_index = True,right_index = True)

Role       School
Name                              
Kelly  Director of HR          NaN
Sally  Course liaison  Engineering
James          Grader     Business

In [175]:
pd.merge(staff_df,student_df,how = 'right',left_index = True,right_index = True)
print(student_df[student_df['School']  == 'Business'].index)
print(student_df[2:3])
print(student_df.index)

Index(['James'], dtype='object', name='Name')
            School
Name              
Sally  Engineering
Index(['James', 'Mike', 'Sally'], dtype='object', name='Name')


In [176]:
staff_df = staff_df.reset_index()
student_df = student_df.reset_index()
pd.merge(staff_df,student_df,how = 'left',left_on = 'Name',right_on = 'Name')

Name            Role       School
0  Kelly  Director of HR          NaN
1  Sally  Course liaison  Engineering
2  James          Grader     Business

In [177]:
staff_df = pd.DataFrame([{'Name':'Kelly','Role':'Director of HR','Location':'State Street'},
                        {'Name':'Sally','Role':'Course liaison','Location':'Washington Avenue'},
                        {'Name':'James','Role':'Grader','Location':'Washington Avenue'}])

student_df = pd.DataFrame([{'Name':'James','School':'Business','Location':'1024 Billiard Avenue'},
                        {'Name':'Mike','School':'Law','Location':'Fraternity House #22'},
                        {'Name':'Sally','School':'Engineering','Location':'512 Wilson Crescent'}])

pd.merge(staff_df,student_df,how = 'left',left_on = 'Name',right_on = 'Name')


Location_x   Name            Role            Location_y       School
0       State Street  Kelly  Director of HR                   NaN          NaN
1  Washington Avenue  Sally  Course liaison   512 Wilson Crescent  Engineering
2  Washington Avenue  James          Grader  1024 Billiard Avenue     Business

In [178]:
staff_df = pd.DataFrame([{'First Name' : 'Kelly','Last Name':'Desjardins','Role':'Director of HR'},
                        {'First Name':'Sally','Last Name':'Brooks','Role':'Course liaison'},
                        {'First Name':'James','Last Name':'Wilde','Role':'Grader'}])

student_df = pd.DataFrame([{'First Name':'James','Last Name':'Hammond','School':'Business'},
                        {'First Name':'Mike','Last Name':'Smith','School':'Law'},
                        {'First Name':'Sally','Last Name':'Brooks','School':'Engineering'}])

print (staff_df)
print ()
print (student_df)
print ()
print (pd.merge(staff_df,student_df,how = 'inner',left_on = ['First Name','Last Name'],right_on = ['First Name','Last Name']))

print (pd.merge(staff_df,student_df,how = 'outer',left_on = ['First Name','Last Name'],right_on = ['First Name','Last Name']))

  First Name   Last Name            Role
0      Kelly  Desjardins  Director of HR
1      Sally      Brooks  Course liaison
2      James       Wilde          Grader

  First Name Last Name       School
0      James   Hammond     Business
1       Mike     Smith          Law
2      Sally    Brooks  Engineering

  First Name Last Name            Role       School
0      Sally    Brooks  Course liaison  Engineering
  First Name   Last Name            Role       School
0      Kelly  Desjardins  Director of HR          NaN
1      Sally      Brooks  Course liaison  Engineering
2      James       Wilde          Grader          NaN
3      James     Hammond             NaN     Business
4       Mike       Smith             NaN          Law


# Pandas Idioms

In [179]:
import numpy as np

In [180]:
def min_max(row):
    data = row[['Cookware','Electronics']]
    return pd.Series({'min': np.min(data),'max': np.max(data)})

In [181]:
d.apply(min_max,axis = 1)

max        min
0    9.326210   4.410967
1    0.003084   0.000000
2    8.388217   8.194965
3   12.607008   3.870465
4   17.738343   7.549431
5    9.041897   3.334338
6   18.659352   8.428735
7   18.142220   8.918176
8    7.439937   2.136013
9   17.859140   4.886350
10  33.419184  14.926062
11   8.155695   0.062016
12   8.455445   3.466295
13   3.058612   1.646993
14  33.677483  12.086506
15  30.059571  13.567060
16   9.313160   8.545297
17  24.641902  10.166036
18   4.260528   4.090424
19   8.701642  -0.057965
20  51.318405  30.363329
21  31.436846  13.750523
22  36.671054  11.831839

In [182]:
d[['Cookware','Electronics']]

Cookware  Electronics
0    4.410967     9.326210
1    0.000000     0.003084
2    8.194965     8.388217
3    3.870465    12.607008
4    7.549431    17.738343
5    3.334338     9.041897
6    8.428735    18.659352
7    8.918176    18.142220
8    2.136013     7.439937
9    4.886350    17.859140
10  14.926062    33.419184
11   8.155695     0.062016
12   3.466295     8.455445
13   1.646993     3.058612
14  12.086506    33.677483
15  13.567060    30.059571
16   8.545297     9.313160
17  10.166036    24.641902
18   4.260528     4.090424
19   8.701642    -0.057965
20  30.363329    51.318405
21  13.750523    31.436846
22  11.831839    36.671054

In [183]:
d[2:][['Cookware','Electronics']]

Cookware  Electronics
2    8.194965     8.388217
3    3.870465    12.607008
4    7.549431    17.738343
5    3.334338     9.041897
6    8.428735    18.659352
7    8.918176    18.142220
8    2.136013     7.439937
9    4.886350    17.859140
10  14.926062    33.419184
11   8.155695     0.062016
12   3.466295     8.455445
13   1.646993     3.058612
14  12.086506    33.677483
15  13.567060    30.059571
16   8.545297     9.313160
17  10.166036    24.641902
18   4.260528     4.090424
19   8.701642    -0.057965
20  30.363329    51.318405
21  13.750523    31.436846
22  11.831839    36.671054

In [215]:
def min_max(row):
    data = row[['Cookware','Electronics']]
    row['max'] = np.max(data)
    row['min'] = np.min(data)
    return row
d.apply(min_max,axis = 1)

Unnamed: 0     City Name  Electronics  Farm Fresh  Food Services  \
Fashion                                                                        
65.887485            0       Asansol     9.326210    4.875992       0.321805   
80.971502            1     Bhagalpur     0.003084    0.000000       0.000000   
236.798917           2  Bhubaneshwar     8.388217    1.332556       3.125235   
91.584659            3      Bilaspur    12.607008    0.749061       0.704988   
106.258585           4       Burdwan    17.738343    6.738923       0.071279   
60.443088            5       Cuttack     9.041897    0.498090       1.327800   
150.641068           6    Darjeeling    18.659352    0.000000       1.746653   
120.210377           7       Deoghar    18.142220    1.640327       0.076467   
29.799165            8       Dhanbad     7.439937    0.088500       1.181627   
113.167080           9      Durgapur    17.859140    6.602162       1.529470   
261.505175          10       Gangtok    33.419184    1.757347       4.128672   
218.248316          11      Guwahati     0.062016    3.303046       7.755597   
46.527830           12    Jamshedpur     8.455445    0.335354       3.034632   
43.378136           13        Jorhat     3.058612    0.645133       0.057150   
211.929732          14     Kharagpur    33.677483    7.337815      29.651620   
444.901968          15       Kolkata    30.059571   10.099553       9.465909   
174.647373          16        Nagpur     9.313160    3.845942       9.302375   
256.682641          17         Patna    24.641902    4.660856       5.749779   
126.127415          18        Raipur     4.090424    1.943917       6.825529   
231.870906          19        Ranchi    -0.057965    4.976697       4.171031   
437.610881          20     Sambalpur    51.318405   39.609752       1.147256   
286.042480          21       Silchar    31.436846    0.137636       0.006133   
504.925297          22      Siliguri    36.671054   10.278085       6.235079   

                Shoes  Home Essentials  Home Fashion  Healthcare  \
Fashion                                                            
65.887485    0.052578         0.026259      7.600607   52.124781   
80.971502    1.482084         0.027802      5.781903    0.000000   
236.798917   9.178001         6.705987     27.460260  114.082629   
91.584659    3.211575         4.547712      9.595964   52.997631   
106.258585   0.559170         0.023667     10.427295   65.046538   
60.443088    1.963191         2.501399      8.693068   42.899273   
150.641068   1.984217         0.068453     18.266982   76.430220   
120.210377   4.348105         0.953865     16.454188   94.988374   
29.799165    0.178593         0.027974      5.292497   21.228914   
113.167080   2.867845         3.192212     12.086807   68.058282   
261.505175  10.446536         0.146881     37.033599  115.432057   
218.248316   7.695406         4.699615     21.224135   79.307993   
46.527830    1.737390         0.490392      8.904375   35.982107   
43.378136    0.754509         0.013736      4.508982   16.379859   
211.929732   5.989689         6.565266     17.278501  105.240438   
444.901968   8.818370         2.921959     34.280613  191.210841   
174.647373   8.324793         1.835115     18.193751  113.930598   
256.682641   8.854915         0.028911     31.813404  139.115233   
126.127415   7.933729         0.740549     13.683484   65.284939   
231.870906   7.085250         1.195173     22.947402  104.299345   
437.610881   3.192565         0.002223     65.241926  304.458377   
286.042480   2.276448         0.000000     34.404054  109.670728   
504.925297  12.258729         7.204110     42.812149  136.679356   

            Trolley Bags    ...      Sex Ratio  Per Capita Income  \
Fashion                     ...                                     
65.887485       7.971341    ...            929             100000   
80.971502       0.066169    ...            880              63200   
236.798917     23.739070    ...   

In [223]:
for City in d['Cookware'].unique():
       avg = np.average(d.where(d['Cookware'] == City).dropna()['Electronics'])
       print ('The avg of ' + str(City) + 'is' +str(avg))
    

The avg of 4.41096714055is9.32620953438
The avg of 0.0is0.00308387438585
The avg of 8.19496483527is8.38821700209
The avg of 3.87046478265is12.6070077214
The avg of 7.54943125388is17.7383428349
The avg of 3.33433792317is9.04189702863
The avg of 8.42873527208is18.6593523252
The avg of 8.9181763562is18.1422196846
The avg of 2.13601324333is7.4399372544
The avg of 4.88635016072is17.8591397787
The avg of 14.9260624015is33.4191844126
The avg of 8.15569507036is0.0620156742661
The avg of 3.4662947238is8.4554448068
The avg of 1.64699335835is3.05861152117
The avg of 12.0865058332is33.6774825389
The avg of 13.5670598199is30.0595714318
The avg of 8.54529695115is9.31316017401
The avg of 10.1660358611is24.6419022552
The avg of 4.26052751642is4.09042350161
The avg of 8.7016424871is-0.0579650223071
The avg of 30.363328587is51.318405
The avg of 13.7505227102is31.4368456287
The avg of 11.8318387029is36.6710535124


In [1]:
d

NameError: name 'd' is not defined

In [255]:
for group,frame in d.groupby('Cookware'):
    avg = np.average(frame['Electronics'])
    print ('The average of'+str(group)+ 'is'+str(avg))

The average of0.0is0.00308387438585
The average of1.64699335835is3.05861152117
The average of2.13601324333is7.4399372544
The average of3.33433792317is9.04189702863
The average of3.4662947238is8.4554448068
The average of3.87046478265is12.6070077214
The average of4.26052751642is4.09042350161
The average of4.41096714055is9.32620953438
The average of4.88635016072is17.8591397787
The average of7.54943125388is17.7383428349
The average of8.15569507036is0.0620156742661
The average of8.19496483527is8.38821700209
The average of8.42873527208is18.6593523252
The average of8.54529695115is9.31316017401
The average of8.7016424871is-0.0579650223071
The average of8.9181763562is18.1422196846
The average of10.1660358611is24.6419022552
The average of11.8318387029is36.6710535124
The average of12.0865058332is33.6774825389
The average of13.5670598199is30.0595714318
The average of13.7505227102is31.4368456287
The average of14.9260624015is33.4191844126
The average of30.363328587is51.318405


In [222]:
d

Unnamed: 0     City Name   Wellness   Cookware   Crockery  Electronics  \
0            0       Asansol   4.956842   4.410967   4.966021     9.326210   
1            1     Bhagalpur   0.000000   0.000000   0.003084     0.003084   
2            2  Bhubaneshwar   4.162359   8.194965  13.000041     8.388217   
3            3      Bilaspur   1.174011   3.870465   4.533087    12.607008   
4            4       Burdwan   7.243664   7.549431   9.280459    17.738343   
5            5       Cuttack   0.787539   3.334338   4.585993     9.041897   
6            6    Darjeeling   1.295136   8.428735  12.983429    18.659352   
7            7       Deoghar   0.885450   8.918176   8.383538    18.142220   
8            8       Dhanbad   0.284988   2.136013   2.750970     7.439937   
9            9      Durgapur   5.499619   4.886350   6.966444    17.859140   
10          10       Gangtok   0.385607  14.926062  16.498030    33.419184   
11          11      Guwahati   3.451491   8.155695  14.045989     0.062016   
12          12    Jamshedpur   1.149294   3.466295   4.294050     8.455445   
13          13        Jorhat   0.511969   1.646993   2.625684     3.058612   
14          14     Kharagpur   7.161369  12.086506  10.758329    33.677483   
15          15       Kolkata  10.557638  13.567060  18.667570    30.059571   
16          16        Nagpur   2.898543   8.545297   9.444006     9.313160   
17          17         Patna   6.222084  10.166036  16.315678    24.641902   
18          18        Raipur   1.438922   4.260528   5.176812     4.090424   
19          19        Ranchi   3.519253   8.701642  15.352618    -0.057965   
20          20     Sambalpur   4.967846  30.363329  29.881101    51.318405   
21          21       Silchar   4.624118  13.750523  19.602239    31.436846   
22          22      Siliguri   6.962590  11.831839  18.062679    36.671054   

    Farm Fresh     Fashion  Food Services      Shoes         ...          \
0     4.875992   65.887485       0.321805   0.052578         ...           
1     0.000000   80.971502       0.000000   1.482084         ...           
2     1.332556  236.798917       3.125235   9.178001         ...           
3     0.749061   91.584659       0.704988   3.211575         ...           
4     6.738923  106.258585       0.071279   0.559170         ...           
5     0.498090   60.443088       1.327800   1.963191         ...           
6     0.000000  150.641068       1.746653   1.984217         ...           
7     1.640327  120.210377       0.076467   4.348105         ...           
8     0.088500   29.799165       1.181627   0.178593         ...           
9     6.602162  113.167080       1.529470   2.867845         ...           
10    1.757347  261.505175       4.128672  10.446536         ...           
11    3.303046  218.248316       7.755597   7.695406         ...           
12    0.335354   46.527830       3.034632   1.737390         ...           
13    0.645133   43.378136       0.057150   0.754509         ...           
14    7.337815  211.929732      29.651620   5.989689         ...           
15   10.099553  444.901968       9.465909   8.818370         ...           
16    3.845942  174.647373       9.302375   8.324793         ...           
17    4.660856  256.682641       5.749779   8.854915         ...           
18    1.943917  126.127415       6.825529   7.933729         ...           
19    4.976697  231.870906       4.171031   7.085250         ...           
20   39.609752  437.610881       1.147256   3.192565         ...           
21    0.137636  286.042480       0.006133   2.276448         ...           
22   10.278085  504.925297       6.235079  12.258729         ...           

    Area (km2)  Child Population  Sex Ratio  Per Capita Income  \
0        49.00             60183        929             100000   
1       342.00             54818        880              63200   
2       135.00             81847        890              98095   
3       345.80            407835        94

In [226]:
d = d.set_index('Crockery')
def fun(item):
    if item <5:
        return 0
    if item< 8:
        return 1
    return 2
for group,frame in d.groupby(fun):
    print ('There are'+str(len(frame))+'entries in group'+str(group)+'for processing')
d

There are7entries in group0for processing
There are2entries in group1for processing
There are14entries in group2for processing


Unnamed: 0     City Name   Wellness  Electronics  Farm Fresh  \
Crockery                                                                  
4.966021            0       Asansol   4.956842     9.326210    4.875992   
0.003084            1     Bhagalpur   0.000000     0.003084    0.000000   
13.000041           2  Bhubaneshwar   4.162359     8.388217    1.332556   
4.533087            3      Bilaspur   1.174011    12.607008    0.749061   
9.280459            4       Burdwan   7.243664    17.738343    6.738923   
4.585993            5       Cuttack   0.787539     9.041897    0.498090   
12.983429           6    Darjeeling   1.295136    18.659352    0.000000   
8.383538            7       Deoghar   0.885450    18.142220    1.640327   
2.750970            8       Dhanbad   0.284988     7.439937    0.088500   
6.966444            9      Durgapur   5.499619    17.859140    6.602162   
16.498030          10       Gangtok   0.385607    33.419184    1.757347   
14.045989          11      Guwahati   3.451491     0.062016    3.303046   
4.294050           12    Jamshedpur   1.149294     8.455445    0.335354   
2.625684           13        Jorhat   0.511969     3.058612    0.645133   
10.758329          14     Kharagpur   7.161369    33.677483    7.337815   
18.667570          15       Kolkata  10.557638    30.059571   10.099553   
9.444006           16        Nagpur   2.898543     9.313160    3.845942   
16.315678          17         Patna   6.222084    24.641902    4.660856   
5.176812           18        Raipur   1.438922     4.090424    1.943917   
15.352618          19        Ranchi   3.519253    -0.057965    4.976697   
29.881101          20     Sambalpur   4.967846    51.318405   39.609752   
19.602239          21       Silchar   4.624118    31.436846    0.137636   
18.062679          22      Siliguri   6.962590    36.671054   10.278085   

              Fashion  Food Services      Shoes  Home Essentials  \
Crockery                                                           
4.966021    65.887485       0.321805   0.052578         0.026259   
0.003084    80.971502       0.000000   1.482084         0.027802   
13.000041  236.798917       3.125235   9.178001         6.705987   
4.533087    91.584659       0.704988   3.211575         4.547712   
9.280459   106.258585       0.071279   0.559170         0.023667   
4.585993    60.443088       1.327800   1.963191         2.501399   
12.983429  150.641068       1.746653   1.984217         0.068453   
8.383538   120.210377       0.076467   4.348105         0.953865   
2.750970    29.799165       1.181627   0.178593         0.027974   
6.966444   113.167080       1.529470   2.867845         3.192212   
16.498030  261.505175       4.128672  10.446536         0.146881   
14.045989  218.248316       7.755597   7.695406         4.699615   
4.294050    46.527830       3.034632   1.737390         0.490392   
2.625684    43.378136       0.057150   0.754509         0.013736   
10.758329  211.929732      29.651620   5.989689         6.565266   
18.667570  444.901968       9.465909   8.818370         2.921959   
9.444006   174.647373       9.302375   8.324793         1.835115   
16.315678  256.682641       5.749779   8.854915         0.028911   
5.176812   126.127415       6.825529   7.933729         0.740549   
15.352618  231.870906       4.171031   7.085250         1.195173   
29.881101  437.610881       1.147256   3.192565         0.002223   
19.602239  286.042480       0.006133   2.276448         0.000000   
18.062679  504.925297       6.235079  12.258729         7.204110   

           Home Fashion         ...          Area (km2)  Child Population  \
Crockery                        ...                                         
4.966021       7.600607         ...               49.00             60183   
0.003084       5.781903         ...              342.00             54818   
13.000041     27.460260         ...              135.00             81847   
4.533087       9.595964         ...              

In [238]:
import pandas as pd
import numpy as np

In [241]:
d = d.reset_index()

In [250]:
d
d = d.reset_index()
d

level_0  index  Unnamed: 0     City Name   Wellness   Cookware   Crockery  \
0         0      0           0       Asansol   4.956842   4.410967   4.966021   
1         1      1           1     Bhagalpur   0.000000   0.000000   0.003084   
2         2      2           2  Bhubaneshwar   4.162359   8.194965  13.000041   
3         3      3           3      Bilaspur   1.174011   3.870465   4.533087   
4         4      4           4       Burdwan   7.243664   7.549431   9.280459   
5         5      5           5       Cuttack   0.787539   3.334338   4.585993   
6         6      6           6    Darjeeling   1.295136   8.428735  12.983429   
7         7      7           7       Deoghar   0.885450   8.918176   8.383538   
8         8      8           8       Dhanbad   0.284988   2.136013   2.750970   
9         9      9           9      Durgapur   5.499619   4.886350   6.966444   
10       10     10          10       Gangtok   0.385607  14.926062  16.498030   
11       11     11          11      Guwahati   3.451491   8.155695  14.045989   
12       12     12          12    Jamshedpur   1.149294   3.466295   4.294050   
13       13     13          13        Jorhat   0.511969   1.646993   2.625684   
14       14     14          14     Kharagpur   7.161369  12.086506  10.758329   
15       15     15          15       Kolkata  10.557638  13.567060  18.667570   
16       16     16          16        Nagpur   2.898543   8.545297   9.444006   
17       17     17          17         Patna   6.222084  10.166036  16.315678   
18       18     18          18        Raipur   1.438922   4.260528   5.176812   
19       19     19          19        Ranchi   3.519253   8.701642  15.352618   
20       20     20          20     Sambalpur   4.967846  30.363329  29.881101   
21       21     21          21       Silchar   4.624118  13.750523  19.602239   
22       22     22          22      Siliguri   6.962590  11.831839  18.062679   

    Electronics  Farm Fresh     Fashion         ...          Area (km2)  \
0      9.326210    4.875992   65.887485         ...               49.00   
1      0.003084    0.000000   80.971502         ...              342.00   
2      8.388217    1.332556  236.798917         ...              135.00   
3     12.607008    0.749061   91.584659         ...              345.80   
4     17.738343    6.738923  106.258585         ...               59.00   
5      9.041897    0.498090   60.443088         ...              398.00   
6     18.659352    0.000000  150.641068         ...               10.57   
7     18.142220    1.640327  120.210377         ...              337.00   
8      7.439937    0.088500   29.799165         ...             2052.00   
9     17.859140    6.602162  113.167080         ...              154.00   
10    33.419184    1.757347  261.505175         ...               35.00   
11     0.062016    3.303046  218.248316         ...              215.00   
12     8.455445    0.335354   46.527830         ...              209.00   
13     3.058612    0.645133   43.378136         ...                9.00   
14    33.677483    7.337815  211.929732         ...              127.00   
15    30.059571   10.099553  444.901968         ...              185.00   
16     9.313160    3.845942  174.647373         ...              217.60   
17    24.641902    4.660856  256.682641         ...              297.90   
18     4.090424    1.943917  126.127415         ...              226.00   
19    -0.057965    4.976697  231.870906         ...              175.00   
20    51.318405   39.609752  437.610881         ...              670.00   
21    31.436846    0.137636  286.042480         ...              343.00   
22    36.671054   10.278085  504.925297         ...              260.00   

    Child Population  Sex Ratio  Per Capita Income  Population Growth Rate  \
0              60183        929             100000                   11.92   
1              54818        880              63200                   25.36   
2              81847    

In [253]:
d.groupby('Cookware').agg({'Electronics':np.average})

Electronics
Cookware              
0.000000      0.003084
1.646993      3.058612
2.136013      7.439937
3.334338      9.041897
3.466295      8.455445
3.870465     12.607008
4.260528      4.090424
4.410967      9.326210
4.886350     17.859140
7.549431     17.738343
8.155695      0.062016
8.194965      8.388217
8.428735     18.659352
8.545297      9.313160
8.701642     -0.057965
8.918176     18.142220
10.166036    24.641902
11.831839    36.671054
12.086506    33.677483
13.567060    30.059571
13.750523    31.436846
14.926062    33.419184
30.363329    51.318405

In [262]:
(d.groupby('Fashion')['Population'].agg({'avg':  np.average,'sum': np.sum}))

/home/prasoon/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: using a dict on a Series for aggregation
is deprecated and will be removed in a future version
  """Entry point for launching an IPython kernel.


avg      sum
Fashion                     
29.799165   1162472  1162472
43.378136   1091295  1091295
46.527830    631364   631364
60.443088    610189   610189
65.887485    563917   563917
80.971502    400146   400146
91.584659    331030   331030
106.258585   314265   314265
113.167080   566517   566517
120.210377   203123   203123
126.127415  1010433  1010433
150.641068   118805   118805
174.647373  2405665  2405665
211.929732   207604   207604
218.248316   957352   957352
231.870906  1073427  1073427
236.798917   843402   843402
256.682641  1684222  1684222
261.505175   100286   100286
286.042480   172830   172830
437.610881   184000   184000
444.901968  4496694  4496694
504.925297   513264   513264

# Distribution in pandas

In [263]:
import pandas as pd
import numpy as np

In [265]:
np.random.binomial(1,0.5)

1

In [271]:
np.random.binomial(1000,0.5,10)/1000

array([ 0.529,  0.502,  0.493,  0.491,  0.516,  0.488,  0.518,  0.493,
        0.511,  0.493])

In [275]:
chance_of_tornado = 0.01/100
tornado_events = np.random.binomial(1,chance_of_tornado,100000)
two_days_in_a_row = 0
for j in range(1,len(tornado_events)-1):
    if tornado_events[j] == 1 and tornado_events[j-1] == 1:
        two_days_in_a_row += 1
print ('{} tornadoes back to back in {} years'.format(two_days_in_a_row,1000000/365))        

0 tornadoes back to back in 2739.72602739726 years


In [276]:
np.random.uniform(0,1)

0.7406718037592918

In [277]:
np.random.normal(0.75)

2.167693180200067

In [290]:
distribution = np.random.normal(0.75,size = 1000)
np.sqrt(np.sum((np.mean(distribution)-distribution)**2)/len(distribution))

0.99240834963585145

In [291]:
np.std(distribution)

0.99240834963585145

In [292]:
import scipy.stats as stats
stats.kurtosis(distribution)

-0.08892028173669742

In [293]:
stats.skew(distribution)

0.009030143789673137

In [294]:
chi_squared_df2 = np.random.chisquare(2,size=10000)
stats.skew(chi_squared_df2)

2.0116523116503866